# Generated by Django 4.2.2 on 2023-07-05 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sale_date_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 18, 7, 30, 967522)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 18, 7, 30, 966525)),
        ),
    ]
