# Generated by Django 4.2.2 on 2023-07-05 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_following_date_alter_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 19, 51, 0, 794969)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 19, 51, 0, 794969)),
        ),
    ]
